### PR TITLE
Laravel 10.x support

### PR DESCRIPTION
**Pull request by jonnott**
@qschmick @albanh @JamesFreeman Are you able to help again with this next Laravel version bump?

### CODE REVIEW

**Review by qschmick — APPROVED** [review]

**Comment by jonnott** [comment]
Hey @qschmick .. thank for merging 🕺  .. but how come I don't get a contribution credit here? https://github.com/codestudiohq/laravel-totem/releases/tag/v10.0.0

**Comment by qschmick** [comment]
@jonnott Didn't include your commit: https://github.com/codestudiohq/laravel-totem/releases/tag/v10.0.1

**Comment by jonnott** [comment]
Ah ok.. I assumed the point of the major version bump to v10 was for Laravel 10.x support ;)

**Comment by qschmick** [comment]
@jonnott It was, mis-targeted the release

**Pull request merged**
