### PR TITLE
Feature/add table prefix option

### PR DESCRIPTION
**Pull request by qschmick**
This PR is for issue #50 
* Added ability to set Totem table prefix through config/env
* Created new TotemModel class to allow overriding table name for dynamic prefix
* Updated existing migrations to use new config for new users

### CODE REVIEW

**Comment by roshangautam** [comment]
Good stuff. Thanks @qschmick . Probably need some documentation in readme ?

**Comment by roshangautam** [comment]
This conflict might need to be resolved manually. @qschmick can you please take a look ?

**Comment by qschmick** [comment]
@roshangautam Resolved.

**Comment by roshangautam** [comment]
Thanks @qschmick :)

**Pull request merged**
