### PR TITLE
Update TotemRouteServiceProvider.php

### PR DESCRIPTION
**Pull request by qschmick**
Allow custom middleware to be set through .env value. Still defaults to original values.

### CODE REVIEW

**Comment by roshangautam** [comment]
Can you please add this information to Readme ?

**Comment by MASNathan** [comment]
I think that the best course of action would be adding those entries to the config file.

The config file would have
```php
    'web' => [
        'middleware' => env('TOTEM_WEB_MIDDLEWARE', 'web'),
    ],
    'api' => [
        'middleware' => env('TOTEM_API_MIDDLEWARE', 'api'),
    ],
```

and in the `TotemRouteServiceProvider` we would have something like `config('totem.web.middleware')` and  `config('totem.web.middleware')`

**Comment by qschmick** [comment]
@MASNathan That's a great idea, this also opens up the ability to refactor out other features to the config for the web and api workflows in the future.

**Comment by roshangautam** [comment]
Thanks @qschmick @MASNathan

**Pull request merged**
