### PR TITLE
Bug fixes and "disable cache" config option

### PR DESCRIPTION
**Pull request by h-a-s-h**
The "disable cache" config option feature might look a bit messy, but there's no other way I can think of implementing it.

I use the Totem ^3.0 branch because I'm on Laravel v5.6, but I believe the 2 bugs are also present in the 4.0 branch, so a later merge with the head would also be recommended.

### CODE REVIEW

**Review by roshangautam — COMMENTED** [review]
can you please fix the styleci issues?

**Review by roshangautam — COMMENTED** [review]
Am not sure if we want to add an option to disable cache. Can you please break this into multiple PRs? One for disabling cache and one for the rest. Rest looks fine.

**Comment by roshangautam** [comment]
Thanks for all the hard work but I would really appreciate if you submit separate PRs for each fix. It would easy for me to review them separately.

**Comment by h-a-s-h** [comment]
Sorry, I've been busy with this project and couldn't respond.

I'm fairly new to github, and maybe I rushed into doing this PR. How do I break this PR into multiple ones? Do I have to make a realease/tag for each change and PR each of them? Or can I submit a PR for single commits?

Do I delete this PR?

PS I just realized what that styleci issue is. I overlooked that missing comma in the config array.

**Comment by h-a-s-h** [comment]
Also, I fixed the styleci issue in this commit, not included in the PR: https://github.com/h-a-s-h/laravel-totem/commit/4576a9ead0953bf4b70c42d7304a80f53e21da7d

Can I include this commit also?

**Comment by roshangautam** [comment]
@h-a-s-h  Please create new separate PRs for each fix/feature. You can create separate local branches for each fix/feature and send a PR from each of those branches

**Pull request closed without merging**
