### PR TITLE
Update to Laravel  6.0

### PR DESCRIPTION
**Pull request by themazim**
* validationData needs to be public (https://laravel.com/docs/6.x)
* helper moved to static Helper class (https://laravel.com/docs/6.x/helpers)

### CODE REVIEW

**Comment by themazim** [comment]
Sorry, but I have no clue why this is failing. My local tests are passing:
```
PHPUnit 8.3.5 by Sebastian Bergmann and contributors.

..                                                                  2 / 2 (100%)

Time: 463 ms, Memory: 45.27 MB

OK (2 tests, 5 assertions)

```

**Comment by Darunada** [comment]
Hi there, I saw the same thing until I deleted the vendor/ folder and ran `composer update`; after that was I able to see the test failure.

It looks like you missed two: ListSchedule.php:55 and view.blade.php:16.  Correcting this turns the failing test into a warning (because of the http exception it tests).  

Thanks for doing it!

**Comment by themazim** [comment]
> Hi there, I saw the same thing until I deleted the vendor/ folder and ran `composer update`; after that was I able to see the test failure.
> 
> It looks like you missed two: ListSchedule.php:55 and view.blade.php:16. Correcting this turns the failing test into a warning (because of the http exception it tests).
> 
> Thanks for doing it!

Thank you! that did the trick  👍

**Comment by roshangautam** [comment]
Thanks guys, I will take a look later tonight

**Comment by roshangautam** [comment]
Sorry for the delay. This will require a new branch. I will try to wrap this up later today.

**Comment by joaolisboa** [comment]
Any updates on when Laravel 6 support is coming?

**Comment by roshangautam** [comment]
@themazim I apologize for the late response. I have created a new branch 6.0 and changed the target branch but now the tests are failing. Can you please check and fix them?

**Comment by roshangautam** [comment]
FYI. A new version has been tagged for L6.x support. Thanks for the PR @themazim . Really appreciate it

**Pull request merged**
