### PR TITLE
php version ^8.2

### PR DESCRIPTION
**Pull request by khagesh007**

### CODE REVIEW

**Comment by jonnott** [comment]
Doesn't this want to be..

`"php": "^8.0.0|^8.1.0|^8.2.0"`

..so 8.1.x is also still supported?

**Comment by khagesh007** [comment]
yes @jonnott , I am updating my commit

**Comment by qschmick** [comment]
@khagesh007 Can you also update the GitHub action to run 8.2?

https://github.com/codestudiohq/laravel-totem/blob/9.0/.github/workflows/laravel.yml#L12

**Comment by khagesh007** [comment]
> @khagesh007 Can you also update the GitHub action to run 8.2?
> 
> https://github.com/codestudiohq/laravel-totem/blob/9.0/.github/workflows/laravel.yml#L12

Laravel.yml file updated

**Comment by jonnott** [comment]
@khagesh007 This is now all included within https://github.com/codestudiohq/laravel-totem/pull/381 .. so you can probably close this PR and let's focus on the one with it all in..

@roshangautam

**Comment by roshangautam** [comment]
this was merged as part of @jonnott PR #381 Closing as this is now redundant. Appreciate your contribution efforts and sorry for the delay.

**Pull request closed without merging**
