### PR TITLE
update composer to allow laravel 7

### PR DESCRIPTION
**Pull request by tomschlick**

### CODE REVIEW

**Review by qschmick — APPROVED** [review]

**Comment by qschmick** [comment]
@roshangautam Not sure what's up with the CI steps but they appear to just be stuck.

**Comment by roshangautam** [comment]
Thanks guys. I have created a new 7.0 branch for Laravel 7. Trying to fix some failing tests because of mismatching orchestra test bench version. I will close this PR for now. But really appreciate the help as always. 👍

**Comment by roshangautam** [comment]
just released a new version to support L7

**Comment by tomschlick** [comment]
Thanks! 🎉

**Pull request closed without merging**
