### PR TITLE
Update 2019_09_25_103421_update_task_results_duration_type.php

### PR DESCRIPTION
**Pull request by jonnott**
- add missing table name

See https://github.com/codestudiohq/laravel-totem/issues/368

### CODE REVIEW

**Comment by Rowlando13** [comment]
+1 on merging this PR. I just ran into this issue.

**Comment by jonnott** [comment]
> +1 on merging this PR. I just ran into this issue.

You should be able to temporarily fix this yourself by just altering the migration in your project. That's what I did.

**Comment by jonnott** [comment]
Thanks @qschmick .. can you also possibly merge this into the 10.x branch and tag a release there too?

Also, is it possible to switch 10.x to be the main development branch?

**Comment by Rowlando13** [comment]
Thanks for the PR and the merge. I editing the migration to resolve it when it happened.

**Comment by qschmick** [comment]
@jonnott I can't do that, @roshangautam is the only one with permissions to update the default branch.

**Comment by jonnott** [comment]
> @jonnott I can't do that, @roshangautam is the only one with permissions to update the default branch.

@qschmick Doesn't seem to have been any activity in this project from @roshangautam since 2021 according to GitHub contributions graph.

@roshangautam Are you still active in relation to this project, or otherwise can you give full access permissions to @qschmick so he's able to change the default branch as well as tag/create releases?

**Comment by roshangautam** [comment]
> @jonnott I can't do that, @roshangautam is the only one with permissions to update the default branch.

@qschmick I have made you an admin of this repo, please let me know if that didn't work. Hope this helps.

**Comment by jonnott** [comment]
> > @jonnott I can't do that, @roshangautam is the only one with permissions to update the default branch.
> 
> @qschmick I have made you an admin of this repo, please let me know if that didn't work. Hope this helps.

Great news .. thanks @roshangautam !

@qschmick If you could switch to 10.x as the default branch, that'd be awesome..

~~If you could then merge my PRs in this order:~~

~~https://github.com/codestudiohq/laravel-totem/pull/380~~
~~https://github.com/codestudiohq/laravel-totem/pull/379~~
~~https://github.com/codestudiohq/laravel-totem/pull/376~~

~~I am happy to do the necessary rebases between these merges if it saves you time..~~

~~..then I believe we'd be ready for a new PHP 8.2 / Laravel 11 compatible release!~~

**Comment by jonnott** [comment]
> If you could then merge my PRs in this order:
> 
> #380 #379 #376

Alternatively I could pop all these commits onto one branch and PR that, if that makes it easier..

**Comment by jonnott** [comment]
> Alternatively I could pop all these commits onto one branch and PR that, if that makes it easier..

@qschmick I've now made that single PR with all my changes in .. all tests passing: https://github.com/codestudiohq/laravel-totem/pull/381

**Pull request merged**
