### PR TITLE
Laravel 11.x support

### PR DESCRIPTION
**Pull request by jonnott**
@qschmick @tomschlick

### CODE REVIEW

**Comment by jonnott** [comment]
Looks like this needs LaravelCollective's html package to be updated first..

**Comment by itcbilisim** [comment]
@jonnott Could you please inform me about the latest situation?

**Comment by jonnott** [comment]
> @jonnott Could you please inform me about the latest situation?

@itcbilisim The situation is that I've done all the changes that I think are needed to make a Laravel 11 / PHP 8.2 compatible version, just need a maintainer to merge the PRs and tag a new release. I don't have privileges myself to do this.

**Comment by itcbilisim** [comment]
Yes, I saw the commits you made. Why doesn't someone take these transactions and combine them? I think it would be better if we trigger our friends on this issue. You had the authority given to you, but I guess it wasn't enough?

**Comment by jonnott** [comment]
> Yes, I saw the commits you made. Why doesn't someone take these transactions and combine them? I think it would be better if we trigger our friends on this issue. You had the authority given to you, but I guess it wasn't enough?

The original author @roshangautam gave admin access to @qschmick, I think. I've not been given access.

**Comment by itcbilisim** [comment]
@roshangautam @qschmick 
Could you please make the necessary checks to resolve this issue? We have been waiting for a few days for the solution to this problem, we need your help.

**Pull request closed without merging**
