### PR TITLE
Add in the ability to disable database calls on registering

### PR DESCRIPTION
**Pull request by JamesFreeman**
I'm currently having issues installing this package on my dev environment because it doesn't host the database. We have a pretty unique way of setting up our dev system and it's hosted on a remote server to which my local doesn't have access.

It would be nice to be able to install this package on my local and disable the table exists lookup, whilst when actually running it on my actual server it will run normally. 

I've tried to take into account BCs in this PR and it shouldn't break any existing apps. 

Thoughts?

### CODE REVIEW

**Comment by qschmick** [comment]
@JamesFreeman Couldn't you just add the package to not be discovered and then dynamically register it in non-local?

Something like this:

`composer.json` =>
```
"extra": {
    "laravel": {
        "dont-discover": [
            "studio/laravel-totem"
        ]
    }
},
```

`AppServiceProvider` =>
```
public function register()
    {
        if (! $this->app->isLocal()) {
            $this->app->register(TotemServiceProvider::class);
        }
    }
```

**Comment by JamesFreeman** [comment]
I thought about adding this but my local dev does still need to run some of the commands like registering the migration assets etc?

**Comment by qschmick** [comment]
@JamesFreeman I believe #299 will help in your case, waiting for it to be updated with master and I'll get it released.

**Comment by JamesFreeman** [comment]
Perfect, thanks for that. Looking forward to using Totem!

**Pull request closed without merging**
