### PR TITLE
Fix task result migration for branch 5.0

### PR DESCRIPTION
**Pull request by jorgemudry**
It applies the same changes of [this PR](https://github.com/codestudiohq/laravel-totem/pull/207) for branch 5.0.

### CODE REVIEW

**Review by qschmick — APPROVED** [review]

**Comment by vesper8** [comment]
@jorgemudry please merge this.. entire application is broken because of this :(

**Comment by qschmick** [comment]
@jorgemudry Can you merge in master. The CI test was stuck and only @roshangautam has admin rights to override the checks to merge.

**Comment by jorgemudry** [comment]
@PS-Qschmick what do you mean? There is no master branch 😅

**Comment by jorgemudry** [comment]
@vesper8 My application is broken also, that's why I've created this PR, but I can't merge it

**Comment by qschmick** [comment]
@jorgemudry Sorry, I meant the base branch of v5

**Comment by jorgemudry** [comment]
@PS-Qschmick I'm sorry, but I don't understand you. The PR is against the branch `5.0` and I can't merge it. Is that what are you asking me to do?

**Comment by qschmick** [comment]
@jorgemudry I just merged in another PR to the 5.0 branch. Can you merge those changes into this branch and push it up. It fixed some issues with the styling.

**Comment by jorgemudry** [comment]
@PS-Qschmick if you are talking about this PR: https://github.com/codestudiohq/laravel-totem/pull/210 it is for branch `6.0` not `5.0`.

The last commit for branch `5.0` was on Oct 25, 2019.

**Review by roshangautam — APPROVED** [review]

**Comment by roshangautam** [comment]
sorry for the delay, this has now been merged

**Pull request merged**
